---

- name: Enable Mariadb - MariaDB 10.3 CentOS repository list
  copy:
    dest: /etc/yum.repos.d/MariaDB.repo
    content: |
      [mariadb]
      name = MariaDB
      baseurl = http://yum.mariadb.org/10.3/centos7-amd64
      gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck=1

- name: Install Mariadb packages.
  yum:
    state: latest
    name: 
      - mariadb-server
      - MySQL-python

- name: Start and enable Mariadb.
  become: yes
  service:
    name: mariadb
    state: started
    enabled: yes

# Ansible mysql_secure_installation playbook
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password=123
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy my.cnf file.
  template:
    src: my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: '600'

- name: delete anonymous MySQL server user for ansible_hostname 
  mysql_user: 
    user: "" 
    host: ansible.drupal
    state: absent
 
- name: delete anonymous MySQL server user for localhost
  mysql_user:
    user: "" 
    state: absent
 
- name: remove the MySQL test database
  mysql_db:
    db: test 
    state: absent

- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  mysql_db:
    login_user: root
    login_password: '123'
    name: ansible_drupal9
    state: present

- name: Restart Maraidb
  service: 
    name: mariadb 
    state: restarted


